account/urls.py
from django.urls import path
from . import views
urlpatterns=[
    path('register/',views.register,name="register"),
    path('login/',views.login,name="login"),
    path('logout/',views.logout,name='logout'),
    path('changepassword/',views.changepassword,name="changepassword"),
    path('forgetpassword/',views.forgetpassword,name="forgetpassword"),
    path('edituserinfo/',views.edituserinfo,name="edituserinfo"),
    path('showuserinfo/',views.showuserinfo,name="showuserinfo"),
    path('msg/',views.msg,name="msg"),
]

comment/urls.py
from django.urls import path
from . import views,search_views

from  django.conf.urls import url
urlpatterns=[
    path('question/<str:question_type>/',views.post_question,name='post_question'),
    path('',views.show_main,name='main'),
    path('show-other-user',views.show_other_user,name='show_other_user'),
    path('comment',views.commment,name='comment'),
    path('delete',views.delete,name="delete"),
]

dachuang/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include('account.urls')),
    path('main/',include('comment.urls')),
    path('chat/', include('chatroom.urls')),
    path('search/', include('haystack.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comment/models.py
from django.db import models
from account.models import User
class Question(models.Model):
    user=models.ForeignKey(User,on_delete=models.DO_NOTHING)
    question_type=models.CharField(max_length=50)
    question_text=models.CharField(max_length=200)
    question_date=models.DateTimeField(auto_now_add=True)
    question_img=models.ImageField(upload_to='question_img',null=True)
    reward_integral = models.IntegerField(default=0)
    class Meta:
        ordering = ['-question_date']
class Like_record(models.Model):
    from_user=models.ForeignKey(User,on_delete=models.DO_NOTHING,related_name="from_user")
    to_user=models.ForeignKey(User,on_delete=models.DO_NOTHING,related_name="to_user")
    likes=models.IntegerField(default=0)
class Comment(models.Model):
    is_read=models.IntegerField(default=0)
    comment_question=models.ForeignKey(Question,on_delete=models.DO_NOTHING,null=True)
    comment_type=models.IntegerField(default=0)
    comment_user=models.ForeignKey(User,related_name="comment",on_delete=models.DO_NOTHING)
    reply_user=models.ForeignKey(User,related_name="reply",on_delete=models.DO_NOTHING)
    comment_text=models.TextField()
    comment_time=models.DateTimeField(auto_now_add=True)
    parent_comment=models.ForeignKey('self',null=True,on_delete=models.DO_NOTHING,related_name="parent")
    root_comment=models.ForeignKey('self',null=True,on_delete=models.DO_NOTHING,related_name="root")
    comment_img=models.ImageField(upload_to='answer_img',null=True)
    class Meta:
        ordering=['comment_time']
class History_record(models.Model):
    user=models.ForeignKey(User,on_delete=models.DO_NOTHING)
    viewed_question=models.ForeignKey(Question,on_delete=models.DO_NOTHING)
    view_time=models.DateTimeField(auto_now_add=True)
    class Meta:
        ordering=['-view_time']
class Admire_record(models.Model):
    user=models.ForeignKey(User,on_delete=models.DO_NOTHING,related_name='who_admire')
    question=models.ForeignKey(Question,on_delete=models.DO_NOTHING)
    admire_comment=models.ForeignKey(Comment,on_delete=models.DO_NOTHING)
    admire_user=models.ForeignKey(User,on_delete=models.DO_NOTHING,related_name='admire_who')
    admire_time=models.DateTimeField(auto_now_add=True)
    is_admired=models.IntegerField(default=0)
    is_read=models.IntegerField(default=0)
class Initial_integral(models.Model):
    user=models.ForeignKey(User,on_delete=models.DO_NOTHING)
    is_aquired=models.IntegerField(default=0)
# Create your models here.

comment/views.py
from django.shortcuts import render,redirect
from .models import Question,Like_record,Comment,History_record,Admire_record,Initial_integral
from django.urls import reverse
from account.models import User,Userinfo
from .form import post_question_form,comment_form
from django.http import JsonResponse,HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.core.paginator import Paginator
from comment.models import History_record
from comment.models import Comment

from itertools import chain
@csrf_exempt
def post_question(request,question_type):
    username=request.session.get('username',default=None)
    user=User.objects.get(username=username)
    context0={}
    try:
        context0['your_headimg']=Userinfo.objects.get(user=user).headimg.url
    except:
        context0['your_headimg']=''
    if request.method=="POST":
        # question_type=request.session.get('question_type',default=None)
        username=request.session.get('username',default=None)
        if username:
            question_type=request.POST['question_type']
            reward_integral=int(request.POST['reward_integral'])
            question_form=post_question_form(request.POST,request.FILES)
            if question_form.is_valid():
                question_text=question_form.cleaned_data['question_text']
                question_img=question_form.cleaned_data['question_img']
                question=Question(user=user,question_text=question_text,question_img=question_img,question_type=question_type,reward_integral=reward_integral)
                user.integral-=reward_integral
                question.save()
                user.save()
                referer=request.META.get('HTTP_REFERER',reverse('main'))
                return redirect(referer)
        else:
            return redirect(reverse('login'))
    else:
        request.session['question_type']=question_type
        request.session.set_expiry(0)
        question_form=post_question_form(initial={'question_text':'提问最多200字，添加图片效果更好哦'})
        all_questions=Question.objects.filter(question_type=question_type)
        paginator=Paginator(all_questions,6)
        page_num=int(request.GET.get('page',1))
        questions_of_page=paginator.get_page(page_num)
        current_page=questions_of_page.number
        page_range=list(range(max(current_page-2,1),current_page))+list(range(current_page,min(current_page+2,paginator.num_pages)+1))
        context={}
        context['first_shown_page_num']=page_range[0]
        context['last_shown_page_num']=page_range[-1]
        context['page_range']=page_range
        context['question_form']=question_form
        context['questions_of_page']=questions_of_page
        context['question_type']=question_type
        context['max_integral']=user.integral
        context.update(context0)
        return render(request,'question_list.html',context)
@csrf_exempt
def show_main(request):
    username=request.session.get('username',default=None)
    if username:
        user=User.objects.get(username=username)
        integral_record,is_created=Initial_integral.objects.get_or_create(user=user)
        context={}
        marjors = ['jisuanji','jingjiguanli','xinli','waiyu','history','gongxue','lixue','shengming','zhexue','faxue','edu']

        for marjor in marjors:
            context[marjor]=Question.objects.filter(question_type=marjor)[:5]
        if request.method == 'POST':
            if not integral_record.is_aquired:
                if request.POST.get('get_integral'):
                    integral_record.is_aquired=1
                    user.integral+=100
                    integral_record.save()
                    user.save()
                    return JsonResponse({})
        else:
            userinfo=Userinfo.objects.filter(user=user)
            user_comment_msgs,user_admire_msgs=Comment.objects.filter(reply_user=user,is_read=0),Admire_record.objects.filter(admire_user=user,is_read=0)
            user_msgs=chain(user_comment_msgs,user_admire_msgs)
            count=0;
            if userinfo:
                for user_msg in user_msgs:
                    if user_msg.is_read==0:
                        count+=1
            context['msg_num']=count
            if integral_record.is_aquired:
                context['is_aquired']='1'
            try:
                context['welcome_name']=Userinfo.objects.get(user=user).nickname
                context['your_headimg']=Userinfo.objects.get(user=user).headimg.url
            except:
                context['welcome_name']='friend'
                context['your_headimg']=''
            return render(request,'main.html',context)
    else:
        return redirect(reverse('login'))
@csrf_exempt
def show_other_user(request):
    username=request.session.get('username',default=None)
    if username:
        if request.method=="POST":
            like_status=request.POST['like_status']
            to_user_nick_name = request.session.get('other_user_name', '')
            to_user=Userinfo.objects.get(nickname=to_user_nick_name).user
            from_user = User.objects.get(username=username)
            like_record = Like_record.objects.filter(to_user=to_user, from_user=from_user)
            if like_status=="like":
                if like_record:
                    like_record[0].likes=1
                    like_record[0].save()
                else:
                    like_record=Like_record(to_user=to_user,from_user=from_user,likes=1)
                    like_record.save()
                to_user_info=to_user.userinfo.all()[0]
                to_user_info.like_num=to_user_info.like_num+1
                to_user_info.save()
                return JsonResponse({'status':'已赞'})
            else:
                if like_record:
                    like_record[0].likes = 0
                    like_record[0].save()
                else:
                    like_record = Like_record(to_user=to_user, from_user=from_user, likes=0)
                    like_record.save()
                to_user_info = to_user.userinfo.all()[0]
                to_user_info.like_num = to_user_info.like_num - 1
                to_user_info.save()
                return JsonResponse({'status': '点赞'})
        else:
            from_user=User.objects.get(username=username)
            other_user_name=request.GET.get('other_user_name','')
            request.session['other_user_name']=other_user_name
            other_user=Userinfo.objects.get(nickname=other_user_name).user
            other_user_likes_num=Userinfo.objects.get(nickname=other_user_name).like_num
            other_userinfo=Userinfo.objects.filter(user=other_user)
            like_record=Like_record.objects.filter(to_user=other_user,from_user=from_user)
            context={}
            context['other_userinfo']=other_userinfo[0]
            context['like_num']=other_user_likes_num
            context['integral']=other_user.integral
            try:
                context['your_headimg']=Userinfo.objects.get(user=from_user).headimg.url
            except:
                context['your_headimg']=''
            if like_record:
                if like_record[0].likes==1:
                    context['like_status']="已赞"
                else:
                    context['like_status']="点赞"
            else:
                context['like_status'] = "点赞"
            return render(request,'show_other_user.html',context)
    else:
        return redirect(reverse('login'))
@csrf_exempt
def commment(request):
    username=request.session.get('username',default=None)
    if username:
        user = User.objects.get(username=username)
        if request.method=="POST":
            if request.POST.get('comment_type'):
                text_form=comment_form(request.POST)
                comment=Comment()
                if text_form.is_valid():
                    comment.comment_text = text_form.cleaned_data['comment_text']
                parent_comment_id=request.POST['comment_id']
                comment.comment_type=request.POST['comment_type']
                comment.comment_img=request.FILES.get('comment_img')
                comment.comment_user=user
                parent_comment=Comment.objects.filter(pk=parent_comment_id)
                if parent_comment:
                    comment.parent_comment=parent_comment[0]
                    comment.root_comment=parent_comment[0].root_comment if not parent_comment[0].root_comment is None else parent_comment[0]
                    comment.reply_user=parent_comment[0].comment_user
                else:
                    comment.parent_comment=None
                    comment.root_comment=None
                    question_id=request.POST['question_id']
                    comment.comment_question=Question.objects.get(pk=question_id)
                    comment.reply_user=Question.objects.get(pk=question_id).user
                    user.integral+=3
                comment.save()
                user.save()
                data={'comment_text':comment.comment_text,'comment_date':comment.comment_time,'comment_id':comment.pk}
                try:
                    data['nickname']=comment.comment_user.userinfo.all()[0].nickname
                except:
                    data['nickname']=comment.comment_user.username
                return JsonResponse(data)
            else:
                comment_id=request.POST['comment_id']
                question_id=request.POST['question']
                comment = Comment.objects.get(pk=comment_id)
                question=Question.objects.get(pk=question_id)
                if question.user==user:
                    admire_status=request.POST['admire']
                    admire_record = Admire_record()
                    admire_record.admire_comment = comment
                    admire_record.question=question
                    admire_record.user=user
                    admire_record.admire_user=comment.comment_user

comment/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
     <link rel="stylesheet" type="text/css" href="{% static 'css/top.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/iconfont.css' %}" />
    
    {% block title%}<title>Title</title>{% endblock %}
     <link rel="stylesheet" href="https://apps.bdimg.com/libs/jqueryui/1.10.4/css/jquery-ui.min.css">
     <script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
     <script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
     <script src="https://apps.bdimg.com/libs/jquery/1.10.2/jquery.min.js"></script>
     <script src="https://apps.bdimg.com/libs/jqueryui/1.10.4/jquery-ui.min.js"></script>

     {% block extracss %}{% endblock %}
</head>
<body>
	<div class="HEAD">
        <h1>开启愉快的学习之旅</h1>
		<button onclick="window.location.href='/account/login'" style="color: slateblue;float: right;border: none;background-color: greenyellow;padding: 8px 25px;">登出</button>
	</div>
			
	<div class="guid">
	    <ul>
	    <li class="dropdown">
		<button class="dropbtn">   学科    </button>
        <div class="dropdown-content">
        	<a href="{% url 'post_question' 'jisuanji' %}">计算机</a>
        	<a href="{% url 'post_question' 'jingjiguanli' %}">经济管理</a>
        <a href="{% url 'post_question' 'xinli' %}">心理学</a>
        <a href="{% url 'post_question' 'waiyu' %}">外语</a>
        <a href="{% url 'post_question' 'history' %}">文学历史</a>
        <a href="{% url 'post_question' 'gongxue' %}">工学</a>
        <a href="{% url 'post_question' 'lixue' %}">理学</a>
        <a href="{% url 'post_question' 'shengming' %}">生命科学</a>
        <a href="{% url 'post_question' 'zhexue' %}">哲学</a>
        <a href="{% url 'post_question' 'faxue' %}">法学</a>
        <a href="{% url 'post_question' 'edu' %}">教育教学</a>
        </div>
        </li>
        
        
        <li class="dropdown">
		<button class="dropbtn">   传送门    </button>
        <div class="dropdown-content">
        <a href="{% url 'main' %}">首页</a>
        <a href="/account/showuserinfo">你的一切</a>
        </div>
        </li>

        <li class="dropdown">
		<button class="dropbtn">   其他    </button>
        <div class="dropdown-content">
        <a href="{% url 'chat' %}">聊天吧</a>
        </div>
        </li>
        
      <!--   加入导航内容-->
          <li class="top_bar">
            <i class="iconfont icon_search" >
            </i>
            <form  style="float:right;line-height:middle;" role="search" method="get" id="searchform" action="{% url 'haystack_search' %}">
            <input type="search" name="q" placeholder="搜索" required>
            <!--  <button type="submit"><span class="ion-ios-search-strong"></span></button>-->
            </form>
          </li>
        </ul>
	    
      
	</div>
        
        <div class="clear"></div>
        {% block content %}
        {% endblock %}

    
    <div class="return_top">
    	<a href="/account/showuserinfo">
    	<img src="{{ your_headimg }}" class="headimg" alt="向上" id="head_img"/>
    	</a>
    	<a href="javascript:scrollTo(0,0);" >
    	<i class="iconfont icon_up">
       </i>
    	</a>
    </div>
</body>
<script>
    {% block javascript %} 
    {% endblock %}
	$(document).ready(function(){
	$('#txt').keydown(function(ev){
    
    if(ev.keyCode==13&&$('#txt').val()!=''){   
        window.open('https://www.baidu.com/s?wd='+$('#txt').val())
        $('#txt').val('');
    }
   })
	

	
	
});
    {% if not your_headimg %}
        $("#head_img").attr('src','{% static 'images/origin.jpg' %}');
    {% endif %}
    
   
</script>
</html>

comment/templates/base2.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
   <meta name="viewport" content="width=device-width, initial-scale=1" charset="UTF-8">
   <link rel="stylesheet" type="text/css" href="{% static 'css/top.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/iconfont.css' %}" />
    
    {% block title%}<title>Title</title>{% endblock %}
     <link rel="stylesheet" href="https://apps.bdimg.com/libs/jqueryui/1.10.4/css/jquery-ui.min.css">
     <script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
     <script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
     <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.8.0.js"></script>
     <script src="https://apps.bdimg.com/libs/jqueryui/1.10.4/jquery-ui.min.js"></script>
     
    
	<link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="https://cdn.bootcss.com/jquery/2.1.1/jquery.min.js"></script>
	<script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
     {% block extracss %}{% endblock %}
</head>
<body>
	<div class="HEAD">
        <body data-spy="scroll" data-target=".navbar" data-offset="50">
 
<nav class="navbar navbar-inverse navbar-fixed-top">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>                        
			</button>
			<a class="navbar-brand" href="#">一起学习吧</a>
		</div>
		<div>
			<div class="collapse navbar-collapse" id="myNavbar">
				<ul class="nav navbar-nav">
					<li><a href="#section1">计算机</a></li>
					<li><a href="#section2">经济管理</a></li>
					<li><a href="#section3">心理学</a></li>
					
					<li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">文 <span class="caret"></span></a>
						<ul class="dropdown-menu">
							<li><a href="#section41">外语</a></li>
							<li><a href="#section42">文学历史</a></li>
						</ul>
					</li>
					
					<li><a href="#section5">工学</a></li>
					<li><a href="#section6">理学</a></li>
					<li><a href="#sectio7">生命科学</a></li>
					<li><a href="#section8">哲学</a></li>
					<li><a href="#section9">法学</a></li>
					<li><a href="#section10">教育教学</a></li>
				</ul>
			</div>
		</div>
	</div>
</nav>    


        {% block content %}
        {% endblock %}


<div class="return_top">
    	<a href="/account/showuserinfo">
    	<img src="{{ your_headimg }}" class="headimg" alt="向上" id="head_img"/>
    	</a>
    	<a href="javascript:scrollTo(0,0);" >
    	<i class="iconfont icon_up">
       </i>
    	</a>
    </div>

</body>
<script>
    {% block javascript %} 
    {% endblock %}
	$(document).ready(function(){
	$('#txt').keydown(function(ev){
    
    if(ev.keyCode==13&&$('#txt').val()!=''){   
        window.open('https://www.baidu.com/s?wd='+$('#txt').val())
        $('#txt').val('');
    }
   })
	

	
	
});
    {% if not your_headimg %}
        $("#head_img").attr('src','{% static 'images/origin.jpg' %}');
    {% endif %}
    
   
</script>
</html>

comment/templates/question_detail.html
{% extends 'base.html' %}
{% load static %}

    {% block title %}<title>{{ question.question_text }}</title>{% endblock %}
    {% block extracss %} 
	<link href="{% static 'css/question_detail.css' %}" type="text/css" rel="stylesheet" /> 
	{% endblock %}

    {% block content %}
    {% autoescape off %}
    <div class="qus_text" id="root_comment">
    <p>问题:</p>
    {{ question.question_text }}
    <img  style="max-width: 400px; " src="/media/{{ question.question_img }}" alt="" >
    
     <a  href="javascript:scrollToEnd()" id="answer_button" style="float: right;">
        	<i class="iconfont icon_cart" >
        		回答问题
			</i>
       </a>
    </div>
    
    <ul id="comment_block">
    {% for comment in comments %}
    <li class="comment" id="{{ comment.pk }}">
        {% for comment_user_info in comment.comment_user.userinfo.all %}
       
       <div class="user_info">
       	
       	<img src="{{ comment_user_info.headimg.url }}" height="100px" width="100px" >
       	<h3 style="font: 30px;">{{ comment_user_info.nickname }}</h3>
       	
       	<p>{{ comment.comment_time }}</p>
       </div>
       
        {% endfor %}
       
       <div class="text">
        {{ comment.comment_text }}
        {% if comment.comment_img %}
        <img src="/media/{{ comment.comment_img }}" alt="">
        {% endif %}
        <div class="site_bar">
        <a  href="javascript:reply({{ comment.pk }})">
        	<i class="iconfont icon_comment">
			</i>
        </a>
        {% if comment.comment_type == 1 and is_user %}
        
        <a href="javascript:admire({{ comment.pk }})" id="admire{{ comment.pk }}">
        	<i class="iconfont icon_smile">
        		采纳
        	</i>
        </a>
        <a href="javascript:delete({{ comment.id }})" id="del{{ comment.pk }}" style="display:none">删除</a>
        {% endif %}
        </div>
       </div>
       
       

    	<ul class="reply_all" id="fld{{ comment.pk }}">
    {% for reply in comment.root.all %}
    
    <li class="reply" id="{{ reply.pk }}">
    	
    	<div class="reply1">
    		<p>{{ reply.comment_user }}回复：{{ reply.reply_user }}</p>
    	</div>
    	
        <i>{{ reply.comment_text }}</i> 
        <div class="reply2">
        <a href="javascript:reply({{ reply.pk }})">回复</a><br />
        {{ reply.comment_time }}
        </div>
    </li> 
     {% endfor %}
    </ul>
      <a style="text-align: center;" href="javascript:show(fld{{ comment.pk }})">点击显示全部评论</a>
     
    
    <div class="clear"></div> 
    </li>
    {% endfor %}
    
    </ul>
    
    <form action="{% url 'comment' %}" method="post" id="comment_form" enctype="multipart/form-data" name="comment_form">
        {{ comment_form }}
        <input type="file" name="comment_img" id="id_comment_img">
        <input type="hidden" value="0" name="comment_id" id="id_comment_id">
        <input type="hidden" value="{{ question.pk }}" name="question_id">
        <input type="hidden" value="0" name="comment_type" id="id_comment_type" >
        <input type="submit" value="评论">
        <button onclick="answer()" type="button" id="answer_button">回答问题</button>
    </form>
    {% endautoescape %}
    {% endblock %}


<script>
    {% block javascript %}
    window.onload=function(){
        {% for comment in all_comments %}
            check_del_user({{ comment.pk }});
        {% endfor %}
    }
    function check_del_user(id){
        $.get("{% url 'delete' %}",{'able_to_del':'1','id':id},function(data){
        if(data['able_to_del']=='1'){
            $('#del'+id).css('display','block');
        }
});
    }
    {% for admire_record in admire_records %}
        $('#admire'+{{ admire_record.admire_comment.pk }}).text('已采纳');
    {% endfor %}
    <!--window.onerror=function(){return true;}-->
    function reply(id)
    {
        $("#id_comment_id").val(id);
        $('html').animate({scrollTop:$('#comment_form').offset().top},300,function(){
        CKEDITOR.instances['id_comment_text'].focus();
        });
        var comment_id=$('#id_comment_id');
        if (comment_id != '0'){
            $("#answer_button").attr("disabled","true");
        };
    }
    $('#comment_form').submit(function(){
        CKEDITOR.instances['id_comment_text'].updateElement();
        var form_obj=document.getElementById('comment_form');
        var formdata=new FormData(form_obj);
        $.ajax({
            url:'{% url 'comment' %}',
            type:'POST',
            data: formdata,
            cache:false,
            dataType:'json',
            contentType: false,
            processData: false,
            success:function(data){
                var html='<li class="reply" id="'+data['comment_id']+'"><div class="reply1"><p>你的回复:</p></div>'+
       '<i>'+data['comment_text']+'</i>'+'<div class="reply2">'+data['comment_date']+'<a href="javascript:reply('+data['comment_id']+')">回复</a></div></li>';
                var id=$('#id_comment_id').val();
                $('#'+id).append(html);
                $('html').animate({scrollTop:$('#'+data['comment_id']).offset().top},300);
                console.log(data);
            },
            error: function(xhr){
                console.log(xhr);
            }
        });
        return false;
    })
    function answer(){
        $('#id_comment_type').val('1');
        CKEDITOR.instances['id_comment_text'].updateElement();
        var form_obj=document.getElementById('comment_form');
        var formdata=new FormData(form_obj);
        $.ajax({
            url:'{% url 'comment' %}',
            type:'POST',
            data: formdata,
            cache:false,
            dataType:'json',
            contentType: false,
            processData: false,
            success:function(data){
                var html='<li class="comment" id="'+data['comment_id']+'"><div class="user_info"><img src="{{ your_headimg }}" height="100px" width="100px" ><h3>'+data['nickname']+'</h3><p>'+data['comment_date']+'</p></div><div class="text">'+ data['comment_text']+'<a  href="javascript:reply('+data['comment_id']+')"><i class="iconfont icon_comment site_bar"></i></a></div></li>';
                $('#comment_block').prepend(html);
                $('html').animate({scrollTop:$('#'+data['comment_id']).offset().top},300);
                console.log(data);
            },
            error: function(xhr){
                console.log(xhr);
            }
        });
        return false;
    }
    function admire(id){
        var admire_data={'admire':'yes','comment_id':id,'question':{{ question.pk }}};
        var admire_id='#'+'admire'+id;
        if($(admire_id).text()=="已采纳"){
            alert('您已采纳该回答');
            return false;
        }
        $.ajax({
           url:'{% url 'comment' %}',
           type:'POST',
           data:admire_data,
           cache:false,
           success:function(data){
                $(admire_id).text('已采纳');
                console.log(data);
           },
           error:function(xhr){
           	    alert('采纳失败了');
                console.log(xhr);
           }
        });
        return false;
    }
    function show(id){
    	var x=id;
    	if(x.className== 'reply_all'){
    		x.className= 'reply_all_1';
    	}
    	else{
    		x.className='reply_all';
    	}
    	
    }
    
    

    function scrollToEnd(){
		            var h = $(document).height()-$(window).height();
		            $(document).scrollTop(h); 
    }

 

        
    {% endblock %}
</script>